### ISSUE TITLE
Question: using VarSkip primers for poreCov

### ISSUE THREAD

**Issue by replikation** [nebiolabs/VarSkip#1]
Hi,

I was adding your primer scheme into [poreCov](https://github.com/replikation/poreCov) (a SARS-CoV - nanopore analysis pipeline to simplify high throughput analysis). And I wanted to check in, if the current code references are in order for you:

* your primers are stored [here](https://github.com/replikation/poreCov/tree/master/data/external_primer_schemes/nCoV-2019/VarSkipV1a)
* the poreCov help message references it like this:
```
Parameters - nCov genome reconstruction (optional)
    --primerV       Supported primer variants - choose one [default: V3]
                        ARTIC: V1, V2, V3, V4 
                        NEB: VarSkipV1a
                        Other: V1200
```
example run with your primers looks like this (without the need to provide the primer files):
```
nextflow run replikation/poreCov -r 0.11.1 --fastq_pass fastq_pass --primerV VarSkipV1a --update -profile local,docker 
```
thank you and best

**Comment by bwlang** [comment]
I've just noticed this message here! - sorry about the long delay.
I think it's great that you can refer to these primers easily for users of poreCov.
