### ISSUE TITLE
VarSkip V2b Issue

### ISSUE THREAD

**Issue by mattdmem** [nebiolabs/VarSkip#3]
Hello,

I noticed one of the primer names is incorrect:

`varskip-0371` instead of `varskip-0317` e.g.`varskip-0371-1_49_RIGHT_ALT1`

**Comment by bwlang** [comment]
Thanks!

**Comment by valentinelsra** [comment]
Hello,

There is the same problem with file [NEB_VarSkip.scheme.bed](https://github.com/nebiolabs/VarSkip/blob/main/schemes/NEB_VarSkip/V2b/NEB_VarSkip.scheme.bed).

Best regards

**Comment by bwlang** [comment]
thanks @valentinelsra 
fixed in:
f5ff970bd8d4d2b41ac309f0a02aad159ecbf9f9
