### ISSUE TITLE
Error: could not find primer scheme and reference sequence

### ISSUE THREAD

**Issue by claudiateran** [nebiolabs/VarSkip#4]
Hi!
I used the Varskip 2a primers for the first time and I am having issues running medaka in the artic bioinformatics protocol (which is the one I always use when I use the V3 primers). I am using the pipeline described in your page, but getting the same error over and over again:
(artic-ncov2019) Lotorres-mac5:S5-027 admin$ artic minion --threads 4 --read-file /Users/admin/Run_07/porechop/S5-027_BC68.fastq  --skip-nanopolish --scheme-directory /Users/admin/artic-ncov2019/primer_schemes/nCoV-2019/NEB_VarSkip --medaka --medaka-model r941_min_fast_g303 NEB_VarSkip S5-027 --scheme-version 2a
could not find primer scheme and reference sequence, attempting to download
Running:  artic-tools get_scheme NEB_VarSkip --schemeVersion 2a
Could not convert: --schemeVersion = 2a
Run with --help for more information.
scheme download failed

We have used several combinations of commands (includin adding the command --scheme-version) but finally getting the same error, where it doesn't find the primer scheme and the reference sequence. We have created another folder inside the nCoV-2019 folder where the V1, 2, 3 and 4 of the artic primer schemes are located. Inside this new folder (named NEB_VarSkip) we have put the files downloaded from your repository primer.bed, the reference.fasta, the primer.tsv and we even created an insert.bed. Nevertheless, the error remains the same.
Please let me know if there is something I am missing.

Thanks a lot for your help!!

**Comment by bwlang** [comment]
I'm sorry I missed your message earlier.
if you specify the correct set of options to artic minion it will cause it not to try to fetch the primer scheme from the internet. 

In this a case i think you need to specify the --scheme-directory as /Users/admin/artic-ncov2019/primer_schemes (not including the nCoV-2019... portion).
