### ISSUE TITLE
Question about alt primers in V2b

### ISSUE THREAD

**Issue by bede** [nebiolabs/VarSkip#5]
Hi there,
I am documenting widely used primer schemes for sequencing viral pathogens as part of a @pha4ge standardisation effort with the aim of facilitating reuse of viral amplicon sequencing data.

It is my understanding that all of these schemes (`V1a`, `V1a-long`, `V2a`, `V2b`) use primers exactly matching the reference sequence at their respective coordinates. Is this correct?

In particular, I see that the V2b contains two primers marked as `ALT`:
- [`varskip-0317-1_49_RIGHT_ALT1`](https://github.com/nebiolabs/VarSkip/blob/f5ff970bd8d4d2b41ac309f0a02aad159ecbf9f9/schemes/NEB_VarSkip/V2b/NEB_VarSkip.scheme.bed#L98)
- [`varskip-0317-1_57_LEFT_ALT2`](https://github.com/nebiolabs/VarSkip/blob/f5ff970bd8d4d2b41ac309f0a02aad159ecbf9f9/schemes/NEB_VarSkip/V2b/NEB_VarSkip.scheme.bed#L114)

Do these also match the reference sequence exactly at their specified coordinates? If so, I can easily create 7 column primer.bed definitions of these schemes for standardisation purposes. If not, would you be able to share the exact sequences of any non-ref primers?

Perhaps Brad (@bwlang) is able to comment?

With many thanks,
Bede

**Comment by bwlang** [comment]
hi @bede 

The ALTs refer to alternate positions, not alternate sequences.

Also the sequences for the primers are listed in the tsv files.

Yes they all  match the reference nearly exactly.  There maybe one or two bases here and there, but they all align nicely using bowtie or other aligners.

Thanks for your work collecting these!
We are working on making primer-monitor.neb.com more useful for multiplex PCR assays so I hope I can use your work there.

**Comment by bede** [comment]
Thanks @bwlang !
Sorry for missing the TSVs at the root of the repository – just what I was after. One of my objectives with this project is to remove ambiguity between similar schemes with difference alts. Do you know of you any differences to the sequences published here?

**Comment by bwlang** [comment]
these sequences are the ones that we synthesized and include in the kits.  
I think they match the reference nearly exactly, but it should be easy to confirm by alignment if you want to be 100% sure.

**Comment by bede** [comment]
Perfect, thank you very much!
